# Generated by Django 2.1.3 on 2018-11-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
