# Generated by Django 2.1.3 on 2018-11-28 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorited_users',
            field=models.ManyToManyField(related_name='favorite_posts', through='linkinator.Favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='voted_users',
            field=models.ManyToManyField(related_name='voted_posts', through='linkinator.Vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
