# Generated by Django 2.1.3 on 2018-12-02 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkinator', '0007_auto_20181202_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_comments',
            field=models.ManyToManyField(related_name='user_comments', through='linkinator.Post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='linkinator.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linkinator.Post'),
        ),
    ]
