# Generated by Django 2.1.3 on 2018-12-02 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkinator', '0008_auto_20181202_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='post',
            name='user_comments',
            field=models.ManyToManyField(related_name='user_comments', through='linkinator.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
